# Generated by Django 5.0.1 on 2024-04-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_report_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
