# Generated by Django 5.0.1 on 2024-06-12 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contest_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
